### ISSUE TITLE
Standalone Server

### ISSUE THREAD

**Issue by asilvas** [asilvas/node-image-steam#9]
This would enable image-steam to be used as a stand-alone web server w/o the need for creating another project and wrapping the connect middleware.

Example flow:

```
npm install image-steam -g
isteam --isConfig './path/of/my-config.json'
```

Could also enable external services such as `cluster-service` or `forever` ala:

```
npm install cluster-service -g
npm install image-steam
cservice --workers './node_modules/image-steam/scripts/server.js' --isConfig './path/of/my-config.json' --config './cservice/config.json'
```

**Comment by Niklas81** [comment]
Does this mean it cannot be used as a standalone server at this point? I haven't had time to try it out yet, but the project looks promising!

Also, a couple of more things I'm curious about:
* Does it / will it have support for caching using e.g. memcaced? So that the resizing operation only has to happen once within a given time-window, and then the result is cached.
* Does it / will it have some form of protection, when used as a standalone server, against  DDoS / overload attacks?

**Comment by asilvas** [comment]
Thanks @Niklas81 -- Currently it just exposes a connect-middleware for you to inject into your node app, and once this ticket is done you can skip the step of having to wrap the module with your own app.

* Image operations get stored back to the original store to avoid re-processing. It's possible a caching tier may be added in the future as well, but for now this should suffice.
* Once #7 is done documentation will expose the 3 levels of throttling to help provide a high quality of service. But the basic tiers of protection include: 1) Concurrent request tracking (responding with 502 toobusy if exceeded), 2) Storage prefetching semaphore to avoid saturating storage, and 3) Processor semaphore to avoid too many image operations in parallel. This does not prevent DDoS attacks, and should be mitigated outside of your service, but should help retain a high quality of service.

**Comment by Niklas81** [comment]
Ok, thanks

**Comment by asilvas** [comment]
This is now live in `0.5.0`.
